### ISSUE TITLE
Circle view - Addition of title

### ISSUE THREAD

**Issue by maitreyie-chavan** [rtCamp/web-stories-wp#6]
**To-Do**

- [x] Enable the `Show Title` option under Story Settings 
- [x] The story title should appear below the respective story circles. Reference - https://codepen.io/maenrique/pen/rNLyqXg
- [x] Longer titles should get capped after a suitable set of characters and include the ellipsis

**Comment by RahiDroid** [comment]
This has been done. Will be updated to dev sites soon.
